### ISSUE TITLE
Multiple fltr not working

### ISSUE THREAD

**Issue by avoronkin** [splittingred/phpThumbOf#12]
phpthumbof 1.1.0, revolution-2.1.0
Multiple fltr not working. Works only the last filter
[[*photo:phpthumbof=`&fltr=gray&fltr=flip|y&w=100&h=100&zc=1`]]

Solution here: https://gist.github.com/905608

**Comment by splittingred** [comment]
Try:

<pre>[[*photo:phpthumbof=`&fltr[]=gray&fltr[]=flip|y&w=100&h=100&zc=1`]]</pre>


(Note the [] )

**Comment by avoronkin** [comment]
Yes, I tried. &fltr[] not working for me.

related post http://modxcms.com/forums/index.php/topic,56733.msg329393.html#msg329393

PHP Version 5.2.9
