### ISSUE TITLE
Is there `onlysrc` option?

### ISSUE THREAD

**Issue by gadamiak** [splittingred/phpThumbOf#13]
In [getResources thumbnail index example][http://rtfm.modx.com/display/ADDON/getResources.Category+Index+Page+with+Thumbnails] there is a call to phpThumbOf in a snippet form with the option in question:

```
[[phpThumbOf? &input=`[[+tv.page-thumb]]` &options=`&w=153&h=200&zc=1`&onlysrc=`1`]]
```

I haven't found any info on it. Is this a valid option and if so, what is it?

**Comment by splittingred** [comment]
There is not; not sure what they are doing there.

**Comment by gadamiak** [comment]
I guess docs will be corrected then?

**Comment by splittingred** [comment]
Done.
