### ISSUE TITLE
Changing image name for PHPthumbof snippet output

### ISSUE THREAD

**Issue by flinx777** [splittingred/phpThumbOf#22]
Love the PHPThumbOf snippet...really amazing.  For a feature, wanted to know if it is possible to output the name as its original name.  Clients have been asking for this for Search Engine purposes.  I know there could potentially be naming conflicts, but any solution or work around (i.e. adding a number at the end if there were multiple instances?) to this potential problem would be welcome.

Thanks again for creating this great snippet!

**Comment by bertoost** [comment]
This one is so nice!!!!

Only missing the sub directories of the original path. This is important to avoid double filenames which normally are stored in separated folders.

So when the original image is;
assets/uploads/images/products/brand-x/image-name.jpg

The cache should be like;
assets/components/phpthumbof/cache/assets/uploads/images/products/brand-x/image-name.jpg

And even better would be to strip the media source paths from the images, but that would be a little bit hard I think.
