### ISSUE TITLE
Image Recreated Every Page Refresh

### ISSUE THREAD

**Issue by AugmentBLU** [splittingred/phpThumbOf#29]
Hello,

I've just updated phpmythumb to 1.3.0 and after every page refresh the thumbs are being recreated which makes the cache useless.  Is there a reason why the images would be regenerated after every page refresh?  I am not clearing the site cache and I have tried disabling the cache manager but this has had no effect.

MODx 2.1.5

Thanks,

Ross

***EDIT 

I just put it back to the version I knew was working (1.2.1) and this does not refresh the cache on each refresh.  I'm just using locally stored images and not Amazon.

**Comment by splittingred** [comment]
Fixed in 1.3.0-pl.
