### ISSUE TITLE
filemanager_path not added to image path

### ISSUE THREAD

**Issue by juro** [splittingred/phpThumbOf#4]
When filemanager_path is set to something (so in filemanager users can see only specified sub-tree), this path is not added to image src in phpthumbof filter. Direct call to phpthumb.php work fine, as well as image preview in image TV.

Example:
real image path: _user/images/image.jpg
filemanager path: _user
path as seen in TVnamed "myimage": images/image.jpg

path in TV preview in manager: /connectors/system/phpthumb.php?h=150&w=150&src=images/image.jpg (WORK FINE, "_user" is added to src param in phpthumb)

This doesn't work:
[[*myimage:phpthumbof=`w=400&amp;h=800]]
phpthumbof doesn't find image. When not using filemanager_path everything is OK

**Comment by krisj** [comment]
try +tv.myimage instead
